### ISSUE TITLE
Controlboard LP66-v1.2

### ISSUE THREAD

**Issue by arhisa2021** [torgeirn/tvlift-hack#1]
Hi @torgeirn,

First of all, I love your project. I found myself in a similar position...:) We have Maclean 866 Smart Lift, which has the same control board as you are mentioning (Picture: 
![61usH-9fWHL](https://github.com/torgeirn/tvlift-hack/assets/129842776/70fe98d1-c932-426e-b5f3-46d9fb849716)

I've learned that it is not IR remote and after a lot of searching, I bumped into this project of yours :)
The only difference I can see in our setup at a glance is that my board is v1.2... Since I don't have any major knowledge in electronics anatomy...I was wondering do you maybe know what the actual difference would be between these boards?
I'm expecting my ESP to arrive in 10-14 days and then I will try via your instruction to do the same...

If you have any suggestions that you could share with an amateur:) I would be very grateful :)

Best Regards
Rok

**Comment by torgeirn** [comment]
I assume this will work fine. Your lift looks identical to mine except for the HW revision on the board. Since I am only "duplicating" the bitpattern from the receiver module, you can probably read the type number of the receiver module on the board to confirm that it matches with whats in the datasheet in this repo.
The receiver module is the one that is red in my images, but I have seen the same type on a blue board. The largest chip on the receiver module should give you a model number. You may need a magnifying glass.
Good luck :)

**Comment by arhisa2021** [comment]
Hi,

Please tell me how can I buy you a cup of coffee :) Thank you, it works!!!!

BR Rok

**Comment by torgeirn** [comment]
> Hi,
> 
> Please tell me how can I buy you a cup of coffee :) Thank you, it works!!!!
> 
> BR Rok

Great!
Will have my morning coffee knowing I helped :)

BR Torgeir

**Comment by bobbieluke1** [comment]
Hi I'm about to do this project, do either of you have an update on if, torgeirn the original installation is still going or if arhisa2021 you got it working.

Thanks for this great work I never would have figured it out otherwise.

**Comment by arhisa2021** [comment]
Hi, I can confirm that it is still working. I followed Torgeirn project and it was a pure success.
Regards
